# Generated by Django 5.0.1 on 2024-07-19 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_contactenquiry_delete_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contactEnquiry',
            new_name='contact',
        ),
    ]
