# Generated by Django 4.1.3 on 2024-07-19 14:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_contactenquiry_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30, null=True)),
                ('lname', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=30, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('Message', ckeditor.fields.RichTextField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='app',
        ),
        migrations.DeleteModel(
            name='contact',
        ),
        migrations.DeleteModel(
            name='userform',
        ),
    ]
